# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='小说名')),
                ('author', models.CharField(blank=True, max_length=10, verbose_name='作者')),
                ('summary', models.TextField(verbose_name='简介')),
                ('image', models.ImageField(upload_to='', verbose_name='小说图片')),
                ('counter', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artapp.book')),
            ],
        ),
    ]
